name: Myrosynthesis
version: 0.2
main: me.deadybbb.myrosynthesis.Myrosynthesis
api-version: 1.20
authors:
  - Ybbb
commands:
  zone:
    description: Управление зонами с эффектами
    usage: /<command> <create|pos1|pos2|toggle|delete|change> [name]